[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Wilson Santos", email = "wilson.santos.dev87@gmail.com"},
]
dependencies = [
    "locust>=2.14.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
